CREATE TYPE unit_role AS ENUM (
    'LORDS',
    'HEROES',
    'MELEE_INFANTRY',
    'MISSILE_INFANTRY',
    'MELEE_CAVALRY',
    'MISSILE_CAVALRY',
    'CHARIOTS',
    'WAR_BEASTS',
    'MONSTROUS_INFANTRY',
    'MONSTERS',
    'WAR_MACHINES',
    'ARTILLERY'
);

ALTER TABLE unit
    ADD COLUMN role unit_role NOT NULL DEFAULT 'MELEE_INFANTRY';