CREATE TYPE unit_role AS ENUM (
    'LORDS', 'HEROES', 'MELEE_INFANTRY', 'MISSILE_INFANTRY',
    'MELEE_CAVALRY', 'MISSILE_CAVALRY', 'CHARIOTS', 'WAR_BEASTS',
    'MONSTROUS_INFANTRY', 'MONSTERS', 'WAR_MACHINES', 'ARTILLERY'
);

CREATE TYPE unit_category_type AS ENUM (
    'REGULAR', 'LEGENDARY', 'LANDMARK', 'RENOWNED', 'RAISED'
);

CREATE TYPE ranged_mode AS ENUM (
    'NONE', 'SINGLE', 'DUAL'
);

CREATE TYPE ability_type AS ENUM (
    'AUGMENT', 'REGENERATION', 'HEX', 'MAGIC_MISSILE', 'WIND',
    'BREATH', 'DIRECT_DAMAGE', 'BOMBARDMENT', 'EXPLOSION',
    'HIDING', 'VORTEX', 'SUMMON'
);

CREATE TYPE building_category AS ENUM (
    'SETTLEMENT', 'PORT', 'MILITARY_RECRUITMENT', 'MILITARY_SUPPORT',
    'DEFENSE', 'INFRASTRUCTURE', 'RESOURCE', 'LANDMARK'
);

CREATE TYPE item_category AS ENUM (
    'ARMOUR', 'ENCHANTED_ITEM', 'TALISMAN', 'WEAPON', 'ARCANE_ITEM'
);

CREATE TYPE item_rarity AS ENUM (
    'COMMON', 'UNCOMMON', 'RARE', 'LEGENDARY', 'CRAFTED'
);

CREATE TYPE climate_status AS ENUM (
    'HABITABLE', 'UNPLEASANT', 'UNINHABITABLE'
);